### ISSUE TITLE
Sorting order for list-views

### ISSUE THREAD

**Issue by jayktee** [dcl-covid-19/mega-map-dev#32]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.
Sort list view for non-mapped categories. 
- Legal (latlong = NULL): (1) Calculate distance between user's zipcode and latlongs for each county that the resource serves (county column = 1), filter for the closest distance. (2) Sort by Hotlines (`legal_hotline`) > Legal Services (`legal_assistance`) > Legal general information (`legal_gen_info`).
- Medical (telehealth = 1): (1) Calculate distance between user's zipcode and latlongs for each county that the resource serves (county column = 1), then filter for the closest distance. (2) within county, sort alphabetically by `provider_addloc`
- Not sure what the sorting will be like in a combined map-list view (i.e. when both physical and phone-only services are in the same view). Thoughts?

(b) What do we need to code next?
- Tagging @akatta13 We will now separate legal_hotline from legal_assistance (currently we are merging both legal services and hotlines into a single category
- @mfincker We previously only had resource for legal resources, i.e. `resource` = legal_assistance, but will now have 3 different categories of legal assistance. I will file a separate issue for adding categories to the dropdown list

**Comment by charliehoffs** [comment]
Based on feedback that 1) it would be helpful for us to display all categories on a map, even for non-location-based services (because it is helpful to know which legal aid providers and CBOs for example, specialize in one's community) and 2) the need to show the address for each entry and 3) or overall re-organization of sort order, I'm going to close this issue!
