### ISSUE TITLE
Ensure information populates for "Medical resources" category > "Victims of domestic violence support" checkbox

### ISSUE THREAD

**Issue by charliehoffs** [dcl-covid-19/mega-map-dev#70]
Pull from Airtable's Domestic Violence resource category "DV Medical Support" tag.

**Comment by chalkedgoose** [comment]
I noticed that all the resources for Domestic Violence fall under the resource type ```dv_resources```

This conflicts with the Query being sent to the Carto API ```SELECT * FROM airtable WHERE resource = 'health' AND status = 1``` since this only fetches ```health``` types. When the filter is selected, you're essentially filtering through many ```health``` types, which won't filter down anything related to the ```dv_resources``` category.

You can see all the medical resources related to Domestic Violence are not in the 'health' resource category
by running this query in Carto 
```
SELECT provider_name, cartodb_id, resource, dv_medical, med_domestic_violence from airtable WHERE dv_medical=1 OR med_domestic_violence=1
```

<img width="1356" alt="Screen Shot 2021-01-23 at 1 44 02 PM" src="https://user-images.githubusercontent.com/26678464/105614855-0fab9700-5d81-11eb-8f87-6ebd25ec2672.png">

**Comment by chalkedgoose** [comment]
@jayktee  
I think an easy-to-use isomorphic or browser-friendly library for constructing SQL queries could help in ailing this bug as well as similar bugs related to filters on the site and make things more reactive, but all the resources I am finding either seem outdated or are exclusively targeting node.js

This library looks fairly promising
https://knexjs.org/

**Comment by chalkedgoose** [comment]
@jayktee Either that or we could roll out our own Query builder for Carto or 
change the data in Carto itself which seems like a bit of work but would solve 
the problem at hand. 

We could of course just include ```dv_resources``` in our query 
but I feel like that would dilude the search results a bit since it 
would be inclusive of ```dv_resources``` that are not necessarily 
related to the ```health```  types in this collection.

**Comment by calba5141114** [comment]
It looks like ```med_domestic_violence``` should have the same data as ```dv_resources```
so I'm going to continue to look into the problem since it should be showing up in first query

**Comment by chalkedgoose** [comment]
The issue should be resolved.

**Comment by charliehoffs** [comment]
_Amazing!!_ Thank you @calba5141114 !! I just tried checking it out on the staging link https://dcl-covid-19.github.io/mega-map-dev/#/, but my staging link page is blank for some reason (probably something on my end, I "cleared browsing data" in my Chrome web browser, and it still is blank, but it could easily be something else). Once I can take this for a spin and check it out, I'm so excited for us to push to AWS and finally resolve this bug!
